name: Create Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test_shulker_box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        working-directory: ${{ github.workspace }}/shulker-box
        run: make test
  build_release:
    runs-on: ubuntu-latest
    needs: [test_shulker_box]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Build Releases
        working-directory: ${{ github.workspace }}/shulker-box
        run: make release
      - uses: actions/upload-artifact@v2
        with:
          name: shulker-box-releases
          path: ${{ github.workspace }}/releases/
  # create_release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Release
  #       if: startsWith(github.ref, 'refs/tags/')
  #       uses: softprops/action-gh-release@v1
