name: Create Release
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
jobs:
  test_shulker_box:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        working-directory: ${{ github.workspace }}/shulker-box
        run: make test
  build_release:
    runs-on: ubuntu-latest
    needs: [test_shulker_box]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/checkout@v2
      - name: Build Releases
        working-directory: ${{ github.workspace }}/shulker-box
        run: make release
      - name: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ${{ github.workspace }}/release
